openapi: 3.0.0

servers:
  - description: Film manager backend service
    url: http://localhost:8080/api/

info:
  description: Film Manager - Rest API - Distributed Sys
  version: "0.0.0"
  title: Film Manager API
  contact:
    email: s317783@studenti.polito.it

tags:
  - name: auth
    description: Routes to handle authentication and authorization
  - name: users
    description: Routes to handle user operations
  - name: films
    description: Routes to handle films operations
  - name: reviews
    description: Routes to handle review operations

paths:
  /auth/login:
    post:
      summary: Log in a user
      tags:
        - auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./schemas/dtos/auth/LoginRequest.json"
      responses:
        "200":
          description: Login Successful
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/users/UserResponse.json"
        "401":
          description: Wrong credentials
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/errors/BaseError.json"
        "400":
          description: Missing credentials
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/errors/BadRequestError.json"

  /films/public:
    get:
      summary: retrieve a paged list of public films
      tags:
        - films
      parameters:
        - in: query
          name: paging
          schema:
            $ref: "#/components/schemas/Paging"
      responses:
        "200":
          description: Returns a page of public films
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/films/PublicFilmsResponse.json"

  /films/public/{id}:
    get:
      summary: retrieve the information of a public film with the given id
      tags:
        - films
      parameters:
        - in: path
          name: id
          schema:
            type: "integer"
            format: "int64"
          required: true
      responses:
        "200":
          description: Returns a page of public films
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/films/PublicFilmResponse.json"
        "404":
          description: No film with this id
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/errors/BaseError.json"

  /reviews/{:filmId}:
    get:
      summary: retrieve a paged list of reviews for the given filmId
      tags:
        - reviews
      parameters:
        - in: path
          name: filmId
          schema:
            type: "integer"
            format: "int64"
          required: true
        - in: query
          name: paging
          schema:
            $ref: "#/components/schemas/Paging"
      responses:
        "200":
          description: Returns a page of reviews for the given filmId
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/reviews/ReviewsResponse.json"
        "404":
          description: No public film with this id
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/errors/BaseError.json"
  /reviews/{:filmId}/{:reviewerId}:
    get:
      summary: retrieve the information of a specific review of a given film
      tags:
        - review
      parameters:
        - in: path
          name: filmId
          schema:
            type: "integer"
            format: "int64"
          required: true
        - in: path
          name: reviewerId
          schema:
            type: "integer"
            format: "int64"
          required: true
      responses:
        "200":
          description: Returns the requested Review
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/reviews/ReviewResponse.json"
        "404":
          description: No review with this id
          content:
            application/json:
              schema:
                $ref: "./schemas/dtos/errors/BaseError.json"

components:
  schemas:
    Paging:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
